### ISSUE TITLE
CentOS 7 and Fedora 24 no python3-pyroute2 RPM package

### ISSUE THREAD

**Issue by xning** [xning/procszoo#59]
Hence need installed by *pip3*, need add this to the README.md.

**Comment by xning** [comment]
CentOS 7 has not *pip3*.

**Comment by vfreex** [comment]
maybe we need a requirements.txt?

**Comment by xning** [comment]
@vfreex hence will install these requirements if we install procszoo by *pip* or *pip3*, right?

**Comment by xning** [comment]
@vfreex I think if could resolve such problem, yes, we need such file.

**Comment by xning** [comment]
python-pyroute-0.3.15.el6 issue 

     >>> from pyroute2 import IW
     >>> iw = IW()
     Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
       File "/usr/lib/python2.6/site-packages/pyroute2/__init__.py", line 90, in __new__
         return cls.registry['class'](*argv, **kwarg)
       File "/usr/lib/python2.6/site-packages/pyroute2/iwutil.py", line 169, in __init__
         self.bind(groups, async)
       File "/usr/lib/python2.6/site-packages/pyroute2/netlink/nl80211/__init__.py", line 646, in bind
         groups, None, async)
       File "/usr/lib/python2.6/site-packages/pyroute2/netlink/generic/__init__.py", line 37, in bind
         msg = self.discovery(proto)
       File "/usr/lib/python2.6/site-packages/pyroute2/netlink/generic/__init__.py", line 72, in discovery
         raise err
     pyroute2.netlink.NetlinkError: (2, 'No such file or directory')

**Comment by xning** [comment]
To create *macvtap*, need latest version. I installed the *pyroute2* by *pip*.

**Comment by xning** [comment]
Because *pyroute2.IW* failed on CentOS6, hence wrapper some functions by *iwconfig* to replace the module. Hence add a require *wireless-tools*.
